name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Grant write permissions to the contents (necessary for pushing)
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v4

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you need

      # 3. Install dependencies in the 'frontend' directory
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      # 4. Build the React app
      - name: Build
        run: npm run build
        working-directory: ./frontend

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
          # Optionally, specify the branch to deploy to
          # publish_branch: gh-pages
